# Имя создаваемого контейнера
identidock:
    # Создаем образ из образа
    image: egorrich/identidock:auto

    # открываем порты наружу "HOST:CONTAINER"
    ports: 
        - "80:9090"
        - "9191:9191"

    # Объявление установления соединения из контейнера identidock c контейнером dnmonster.
    # Compose обеспечивает правильный порядок запуска контейнеров.
    links: 
        - dnmonster
        - redis

# Определение нового контейнера dnmonster
dnmonster:
    image: amouat/dnmonster:1.0

# Определение нового контейнера redis
redis:
    image: redis