# Имя создаваемого контейнера
identidock:
    # Сообщает что образ данного контейнера должен быть создан
    # из Dockerfile, расположенного в текущем каталоге (.)
    build: .
    # Так же можно создать образ из образа
    # image: python:3.7
    
    # Служит для объявления открытых портов.
    ports:
        - "5000:5000"
    
    # Служит для определения значений переменных окружения.
    environment:
        ENV: DEV
    
    # Служит для определения томов. В данном случае определено монтирование подкаталога app
    # из текущего каталога на каталог /app внутри контейнера.
    volumes:
        - ./app:/app
    
    # Объявление установления соединения из контейнера identidock c контейнером dnmonster.
    # Compose обеспечивает правильный порядок запуска контейнеров.
    links: 
        - dnmonster
        - redis

# Определение нового контейнера dnmonster
dnmonster:
    image: amouat/dnmonster:1.0

# Определение нового контейнера redis
redis:
    image: redis